name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Ou 'master', dependendo da sua branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Criar o arquivo env.js dinamicamente
        run: |
          # O comando abaixo cria a pasta js (se não existir) e o arquivo env.js
          mkdir -p js
          echo "${{ secrets.FIREBASE_ENV_CONTENT }}" > js/env.js

      - name: Deploy para o GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # Pasta onde está seu index.html
          branch: gh-pages # O site será publicado nesta branch automática